### PR TITLE
Change preflight response status code to 204

### LINKED ISSUE #50: Warning Cross-Origin Read Blocking (CORB)
I receive the message only on chrome and only on the aws/forge server (not in localhost - homestead). Everything seems to work well.

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api-staging.myapp.io/api/shop/customer with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

I noticed that the preflight don't show the message "Preflight OK" on the aws/forge server. But yes on the localhost.

Laravel 5.7.15
php: 7.2.5
laravel-cors 1.4
vuejs 3.6.2 (vue-cli)

### PR DESCRIPTION
**Pull request by rosswilson252**
Fixes #50

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by d-pollard** [comment]
This is amazing!

**Comment by adamtester** [comment]
I'm sure the response needs to be blank though?

https://httpstatuses.com/204
`A 204 response is terminated by the first empty line after the header fields because it cannot contain a message body.`

And Googles docs say:
`This is specific to non-empty responses with a status code other than 204 `


I haven't actually tested this PR though!


EDIT: Reading though again I don't think it matters much

**Comment by mipapo** [comment]
204 needs to be an empty response - This Merge can result in duplicate Requests in the end! (at least in Chrome)

**Pull request merged**
